### ISSUE TITLE
paging  or drop down load the update at index for show data?

### ISSUE THREAD

**Issue by krircc** [mcux/kylyp#17]
paging  or drop down load the update at index? 
which one is better?

**Comment by ivanceras** [comment]
Did you mean paging or infinite scrolling? I think paging would be better for now. The infinite scrolling in what you see in discourse take into consideration of skipping multiples pages when scrolled really fast. This requires a lot of clever javascript in order to make it right or else blow the performance of the forum. Paging is simple and doesn't require much clever coding. Discourse also provides paging when javascript is disabled on the browser.

**Comment by krircc** [comment]
@ivanceras  ok  I will do this thing  ,   paging is commonly used . choice it first.

**Comment by krircc** [comment]
@ivanceras pagination id done.  do you have some ideas about Search in site.
